// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, user_id, name, status, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchAgents = `-- name: SearchAgents :many
SELECT id, user_id, name, status, created_at, updated_at FROM agents
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::agent_status IS NULL OR status = $2::agent_status)
ORDER BY created_at ASC
LIMIT $3::integer
`

type SearchAgentsParams struct {
	UserID      *uuid.UUID
	Status      *AgentStatus
	ResultLimit int32
}

func (q *Queries) SearchAgents(ctx context.Context, arg SearchAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, searchAgents, arg.UserID, arg.Status, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgent = `-- name: UpsertAgent :exec
INSERT INTO agents (id, user_id, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
`

type UpsertAgentParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Status    AgentStatus
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) error {
	_, err := q.db.Exec(ctx, upsertAgent,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
