// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_identities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findAuthIdentityByProviderSubject = `-- name: FindAuthIdentityByProviderSubject :one
SELECT id, user_id, provider, provider_subject, created_at FROM auth_identities WHERE provider = $1 AND provider_subject = $2
`

type FindAuthIdentityByProviderSubjectParams struct {
	Provider        string
	ProviderSubject string
}

func (q *Queries) FindAuthIdentityByProviderSubject(ctx context.Context, arg FindAuthIdentityByProviderSubjectParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, findAuthIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAuthIdentity = `-- name: UpsertAuthIdentity :exec
INSERT INTO auth_identities (id, user_id, provider, provider_subject, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, provider_subject) DO UPDATE SET
    user_id = EXCLUDED.user_id
`

type UpsertAuthIdentityParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderSubject string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertAuthIdentity(ctx context.Context, arg UpsertAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.CreatedAt,
	)
	return err
}
