// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBoardPost = `-- name: GetBoardPost :one
SELECT
  p.id,
  p.author_id,
  p.title,
  p.body,
  p.created_at,
  u.display_name AS author_name,
  u.avatar_url AS author_avatar_url,
  (u.human_verified_at IS NOT NULL)::boolean AS author_verified
FROM board_posts p
JOIN users u ON u.id = p.author_id
WHERE p.id = $1 AND p.hidden_at IS NULL
`

type GetBoardPostRow struct {
	ID              uuid.UUID
	AuthorID        uuid.UUID
	Title           string
	Body            string
	CreatedAt       pgtype.Timestamptz
	AuthorName      string
	AuthorAvatarUrl *string
	AuthorVerified  bool
}

func (q *Queries) GetBoardPost(ctx context.Context, id uuid.UUID) (GetBoardPostRow, error) {
	row := q.db.QueryRow(ctx, getBoardPost, id)
	var i GetBoardPostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorName,
		&i.AuthorAvatarUrl,
		&i.AuthorVerified,
	)
	return i, err
}

const insertBoardPost = `-- name: InsertBoardPost :exec
INSERT INTO board_posts (id, author_id, title, body, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBoardPostParams struct {
	ID        uuid.UUID
	AuthorID  uuid.UUID
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertBoardPost(ctx context.Context, arg InsertBoardPostParams) error {
	_, err := q.db.Exec(ctx, insertBoardPost,
		arg.ID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const insertBoardReply = `-- name: InsertBoardReply :exec
INSERT INTO board_replies (id, post_id, author_id, body, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBoardReplyParams struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	AuthorID  uuid.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertBoardReply(ctx context.Context, arg InsertBoardReplyParams) error {
	_, err := q.db.Exec(ctx, insertBoardReply,
		arg.ID,
		arg.PostID,
		arg.AuthorID,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const listBoardPosts = `-- name: ListBoardPosts :many
SELECT
  p.id,
  p.author_id,
  p.title,
  p.body,
  p.created_at,
  u.display_name AS author_name,
  u.avatar_url AS author_avatar_url,
  (u.human_verified_at IS NOT NULL)::boolean AS author_verified,
  (SELECT COUNT(*) FROM board_replies r WHERE r.post_id = p.id AND r.hidden_at IS NULL)::bigint AS reply_count
FROM board_posts p
JOIN users u ON u.id = p.author_id
WHERE p.hidden_at IS NULL
ORDER BY p.created_at DESC
LIMIT $2::integer OFFSET $1::integer
`

type ListBoardPostsParams struct {
	ResultOffset int32
	ResultLimit  int32
}

type ListBoardPostsRow struct {
	ID              uuid.UUID
	AuthorID        uuid.UUID
	Title           string
	Body            string
	CreatedAt       pgtype.Timestamptz
	AuthorName      string
	AuthorAvatarUrl *string
	AuthorVerified  bool
	ReplyCount      int64
}

// 新着スレッド一覧。著者表示情報と返信数を join/相関で付与。
func (q *Queries) ListBoardPosts(ctx context.Context, arg ListBoardPostsParams) ([]ListBoardPostsRow, error) {
	rows, err := q.db.Query(ctx, listBoardPosts, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardPostsRow{}
	for rows.Next() {
		var i ListBoardPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.AuthorVerified,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardReplies = `-- name: ListBoardReplies :many
SELECT
  r.id,
  r.post_id,
  r.author_id,
  r.body,
  r.created_at,
  u.display_name AS author_name,
  u.avatar_url AS author_avatar_url,
  (u.human_verified_at IS NOT NULL)::boolean AS author_verified
FROM board_replies r
JOIN users u ON u.id = r.author_id
WHERE r.post_id = $1 AND r.hidden_at IS NULL
ORDER BY r.created_at ASC
`

type ListBoardRepliesRow struct {
	ID              uuid.UUID
	PostID          uuid.UUID
	AuthorID        uuid.UUID
	Body            string
	CreatedAt       pgtype.Timestamptz
	AuthorName      string
	AuthorAvatarUrl *string
	AuthorVerified  bool
}

func (q *Queries) ListBoardReplies(ctx context.Context, postID uuid.UUID) ([]ListBoardRepliesRow, error) {
	rows, err := q.db.Query(ctx, listBoardReplies, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardRepliesRow{}
	for rows.Next() {
		var i ListBoardRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.AuthorVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
