// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertListingImages implements pgx.CopyFromSource.
type iteratorForInsertListingImages struct {
	rows                 []InsertListingImagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertListingImages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertListingImages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ListingID,
		r.rows[0].Url,
		r.rows[0].ImageHash,
		r.rows[0].SortOrder,
	}, nil
}

func (r iteratorForInsertListingImages) Err() error {
	return nil
}

// 出品作成時の画像添付を1往復でバッチ挿入する（pgx CopyFrom）。
func (q *Queries) InsertListingImages(ctx context.Context, arg []InsertListingImagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"listing_images"}, []string{"listing_id", "url", "image_hash", "sort_order"}, &iteratorForInsertListingImages{rows: arg})
}
