// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: direct_messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadBySender = `-- name: CountUnreadBySender :many
SELECT sender_id, COUNT(*)::bigint AS unread
FROM direct_messages
WHERE recipient_id = $1 AND read_at IS NULL AND status <> 'HIDDEN'
GROUP BY sender_id
`

type CountUnreadBySenderRow struct {
	SenderID uuid.UUID
	Unread   int64
}

// 自分宛の未読を相手(sender)ごとに集計。受信箱の未読バッジ用。
func (q *Queries) CountUnreadBySender(ctx context.Context, recipientID uuid.UUID) ([]CountUnreadBySenderRow, error) {
	rows, err := q.db.Query(ctx, countUnreadBySender, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUnreadBySenderRow{}
	for rows.Next() {
		var i CountUnreadBySenderRow
		if err := rows.Scan(&i.SenderID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDirectMessage = `-- name: InsertDirectMessage :exec
INSERT INTO direct_messages (id, sender_id, recipient_id, body, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDirectMessageParams struct {
	ID          uuid.UUID
	SenderID    uuid.UUID
	RecipientID uuid.UUID
	Body        string
	Status      MessageStatus
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertDirectMessage(ctx context.Context, arg InsertDirectMessageParams) error {
	_, err := q.db.Exec(ctx, insertDirectMessage,
		arg.ID,
		arg.SenderID,
		arg.RecipientID,
		arg.Body,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const listDirectThread = `-- name: ListDirectThread :many
SELECT id, sender_id, recipient_id, body, status, read_at, created_at FROM direct_messages
WHERE status <> 'HIDDEN'
  AND (
    (sender_id = $1::uuid AND recipient_id = $2::uuid)
    OR (sender_id = $2::uuid AND recipient_id = $1::uuid)
  )
ORDER BY created_at ASC
LIMIT $3::integer
`

type ListDirectThreadParams struct {
	UserA       uuid.UUID
	UserB       uuid.UUID
	ResultLimit int32
}

// 自分(user_a)と相手(user_b)の双方向スレッドを時系列で取得。
func (q *Queries) ListDirectThread(ctx context.Context, arg ListDirectThreadParams) ([]DirectMessage, error) {
	rows, err := q.db.Query(ctx, listDirectThread, arg.UserA, arg.UserB, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectMessage{}
	for rows.Next() {
		var i DirectMessage
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Body,
			&i.Status,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInbox = `-- name: ListInbox :many
SELECT DISTINCT ON (peer)
  peer,
  dm.id,
  dm.sender_id,
  dm.recipient_id,
  dm.body,
  dm.read_at,
  dm.created_at
FROM (
  SELECT id, sender_id, recipient_id, body, status, read_at, created_at, (CASE WHEN sender_id = $1::uuid THEN recipient_id ELSE sender_id END)::uuid AS peer
  FROM direct_messages
  WHERE status <> 'HIDDEN' AND (sender_id = $1::uuid OR recipient_id = $1::uuid)
) dm
ORDER BY peer, dm.created_at DESC
`

type ListInboxRow struct {
	Peer        uuid.UUID
	ID          uuid.UUID
	SenderID    uuid.UUID
	RecipientID uuid.UUID
	Body        string
	ReadAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

// 相手(peer)ごとの最新メッセージ。受信箱の一覧表示用。
func (q *Queries) ListInbox(ctx context.Context, me uuid.UUID) ([]ListInboxRow, error) {
	rows, err := q.db.Query(ctx, listInbox, me)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboxRow{}
	for rows.Next() {
		var i ListInboxRow
		if err := rows.Scan(
			&i.Peer,
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDirectThreadRead = `-- name: MarkDirectThreadRead :exec
UPDATE direct_messages
SET read_at = $1
WHERE recipient_id = $2::uuid
  AND sender_id = $3::uuid
  AND read_at IS NULL
`

type MarkDirectThreadReadParams struct {
	ReadAt pgtype.Timestamptz
	Me     uuid.UUID
	Peer   uuid.UUID
}

// 相手から自分宛の未読を既読化。
func (q *Queries) MarkDirectThreadRead(ctx context.Context, arg MarkDirectThreadReadParams) error {
	_, err := q.db.Exec(ctx, markDirectThreadRead, arg.ReadAt, arg.Me, arg.Peer)
	return err
}
