// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimListingForPurchase = `-- name: ClaimListingForPurchase :one
UPDATE listings
SET status = 'SOLD', sold_at = $1, updated_at = $1
WHERE id = $2
  AND status = 'PUBLISHED'
  AND seller_id <> $3
RETURNING id, seller_id, agent_id, title, description, price, currency, category, condition, status, signature_id, created_at, updated_at, published_at, sold_at
`

type ClaimListingForPurchaseParams struct {
	SoldAt    pgtype.Timestamptz
	ListingID uuid.UUID
	BuyerID   uuid.UUID
}

// 公開中かつ出品者≠購入者の出品を原子的にSOLDへ遷移し、claim行を返す。
// 競合(二重購入)時は条件に合致せず0行 → 呼び出し側がgetPurchasableListingで理由を判定。
func (q *Queries) ClaimListingForPurchase(ctx context.Context, arg ClaimListingForPurchaseParams) (Listing, error) {
	row := q.db.QueryRow(ctx, claimListingForPurchase, arg.SoldAt, arg.ListingID, arg.BuyerID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Category,
		&i.Condition,
		&i.Status,
		&i.SignatureID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.SoldAt,
	)
	return i, err
}

const getListingByID = `-- name: GetListingByID :one
SELECT id, seller_id, agent_id, title, description, price, currency, category, condition, status, signature_id, created_at, updated_at, published_at, sold_at FROM listings WHERE id = $1
`

func (q *Queries) GetListingByID(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingByID, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Category,
		&i.Condition,
		&i.Status,
		&i.SignatureID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.SoldAt,
	)
	return i, err
}

const getListingsByIDs = `-- name: GetListingsByIDs :many
SELECT id, seller_id, agent_id, title, description, price, currency, category, condition, status, signature_id, created_at, updated_at, published_at, sold_at FROM listings WHERE id = ANY($1::uuid[])
`

// 指定idの出品をまとめて取得（いいねした商品一覧のhydrate用。順序は呼び出し側で復元）。
func (q *Queries) GetListingsByIDs(ctx context.Context, ids []uuid.UUID) ([]Listing, error) {
	rows, err := q.db.Query(ctx, getListingsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Listing{}
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Category,
			&i.Condition,
			&i.Status,
			&i.SignatureID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.SoldAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertListingImagesParams struct {
	ListingID uuid.UUID
	Url       string
	ImageHash string
	SortOrder int32
}

const listImagesByListingIDs = `-- name: ListImagesByListingIDs :many
SELECT listing_id, url, sort_order
FROM listing_images
WHERE listing_id = ANY($1::uuid[])
ORDER BY sort_order ASC
`

type ListImagesByListingIDsRow struct {
	ListingID uuid.UUID
	Url       string
	SortOrder int32
}

func (q *Queries) ListImagesByListingIDs(ctx context.Context, listingIds []uuid.UUID) ([]ListImagesByListingIDsRow, error) {
	rows, err := q.db.Query(ctx, listImagesByListingIDs, listingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesByListingIDsRow{}
	for rows.Next() {
		var i ListImagesByListingIDsRow
		if err := rows.Scan(&i.ListingID, &i.Url, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchListings = `-- name: SearchListings :many
SELECT id, seller_id, agent_id, title, description, price, currency, category, condition, status, signature_id, created_at, updated_at, published_at, sold_at FROM listings
WHERE ($1::listing_status IS NULL OR status = $1::listing_status)
  AND ($2::uuid IS NULL OR seller_id = $2::uuid)
  AND ($3::varchar IS NULL OR category = $3::varchar)
  AND ($4::varchar IS NULL OR condition = $4::varchar)
  AND ($5::integer IS NULL OR price >= $5::integer)
  AND ($6::integer IS NULL OR price <= $6::integer)
  AND (
    $7::text IS NULL
    OR title ILIKE '%' || $7::text || '%'
    OR description ILIKE '%' || $7::text || '%'
  )
ORDER BY created_at ASC
LIMIT $8::integer
`

type SearchListingsParams struct {
	Status      *ListingStatus
	SellerID    *uuid.UUID
	Category    *string
	Condition   *string
	MinPrice    *int32
	MaxPrice    *int32
	Keyword     *string
	ResultLimit int32
}

// 有界(7フィルタ)の検索。各条件は narg がNULLなら無効化される（Query Builder不要）。
func (q *Queries) SearchListings(ctx context.Context, arg SearchListingsParams) ([]Listing, error) {
	rows, err := q.db.Query(ctx, searchListings,
		arg.Status,
		arg.SellerID,
		arg.Category,
		arg.Condition,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Keyword,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Listing{}
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Category,
			&i.Condition,
			&i.Status,
			&i.SignatureID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.SoldAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertListing = `-- name: UpsertListing :exec
INSERT INTO listings (
    id, seller_id, agent_id, title, description, price, currency, category, condition,
    status, signature_id, created_at, updated_at, published_at, sold_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    currency = EXCLUDED.currency,
    category = EXCLUDED.category,
    condition = EXCLUDED.condition,
    status = EXCLUDED.status,
    signature_id = EXCLUDED.signature_id,
    updated_at = EXCLUDED.updated_at,
    published_at = EXCLUDED.published_at,
    sold_at = EXCLUDED.sold_at
`

type UpsertListingParams struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	AgentID     *uuid.UUID
	Title       string
	Description string
	Price       int32
	Currency    string
	Category    string
	Condition   string
	Status      ListingStatus
	SignatureID *uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	SoldAt      pgtype.Timestamptz
}

func (q *Queries) UpsertListing(ctx context.Context, arg UpsertListingParams) error {
	_, err := q.db.Exec(ctx, upsertListing,
		arg.ID,
		arg.SellerID,
		arg.AgentID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.Category,
		arg.Condition,
		arg.Status,
		arg.SignatureID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.SoldAt,
	)
	return err
}
