// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimListingForPurchase = `-- name: ClaimListingForPurchase :one
UPDATE listings
SET status = 'SOLD', sold_at = $1, updated_at = $1
WHERE id = $2
  AND status = 'PUBLISHED'
  AND seller_id <> $3
RETURNING id, seller_id, agent_id, title, description, price, currency, category, condition, status, signature_id, created_at, updated_at, published_at, sold_at
`

type ClaimListingForPurchaseParams struct {
	SoldAt    pgtype.Timestamptz
	ListingID uuid.UUID
	BuyerID   uuid.UUID
}

// 公開中かつ出品者≠購入者の出品を原子的にSOLDへ遷移し、claim行を返す。
// 競合(二重購入)時は条件に合致せず0行 → 呼び出し側がgetPurchasableListingで理由を判定。
func (q *Queries) ClaimListingForPurchase(ctx context.Context, arg ClaimListingForPurchaseParams) (Listing, error) {
	row := q.db.QueryRow(ctx, claimListingForPurchase, arg.SoldAt, arg.ListingID, arg.BuyerID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Category,
		&i.Condition,
		&i.Status,
		&i.SignatureID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.SoldAt,
	)
	return i, err
}

const getListingByID = `-- name: GetListingByID :one
SELECT id, seller_id, agent_id, title, description, price, currency, category, condition, status, signature_id, created_at, updated_at, published_at, sold_at FROM listings WHERE id = $1
`

func (q *Queries) GetListingByID(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingByID, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.Category,
		&i.Condition,
		&i.Status,
		&i.SignatureID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.SoldAt,
	)
	return i, err
}

const getListingsByIDs = `-- name: GetListingsByIDs :many
SELECT id, seller_id, agent_id, title, description, price, currency, category, condition, status, signature_id, created_at, updated_at, published_at, sold_at FROM listings WHERE id = ANY($1::uuid[])
`

// 指定idの出品をまとめて取得（いいねした商品一覧のhydrate用。順序は呼び出し側で復元）。
func (q *Queries) GetListingsByIDs(ctx context.Context, ids []uuid.UUID) ([]Listing, error) {
	rows, err := q.db.Query(ctx, getListingsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Listing{}
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Category,
			&i.Condition,
			&i.Status,
			&i.SignatureID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.SoldAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertListingImagesParams struct {
	ListingID uuid.UUID
	Url       string
	ImageHash string
	SortOrder int32
}

const listCategories = `-- name: ListCategories :many
SELECT category, count(*)::bigint AS count
FROM listings
WHERE status = 'PUBLISHED'
GROUP BY category
ORDER BY count DESC, category ASC
`

type ListCategoriesRow struct {
	Category string
	Count    int64
}

// 公開中の出品のカテゴリ別件数。フロントのカテゴリ選択肢/ファセットを取得集合に依存せず提供する。
func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCategories = `-- name: ListDistinctCategories :many
SELECT DISTINCT category FROM listings WHERE category <> '' ORDER BY category
`

// 既存出品のユニークなカテゴリ（AI出品支援に制約として渡し、提案カテゴリを既存集合へ寄せる）。
// カテゴリのライフサイクルは未管理＝シード(abo)由来の既存データを正本とする。
func (q *Queries) ListDistinctCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByListingIDs = `-- name: ListImagesByListingIDs :many
SELECT listing_id, url, sort_order
FROM listing_images
WHERE listing_id = ANY($1::uuid[])
ORDER BY sort_order ASC
`

type ListImagesByListingIDsRow struct {
	ListingID uuid.UUID
	Url       string
	SortOrder int32
}

func (q *Queries) ListImagesByListingIDs(ctx context.Context, listingIds []uuid.UUID) ([]ListImagesByListingIDsRow, error) {
	rows, err := q.db.Query(ctx, listImagesByListingIDs, listingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesByListingIDsRow{}
	for rows.Next() {
		var i ListImagesByListingIDsRow
		if err := rows.Scan(&i.ListingID, &i.Url, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchListings = `-- name: SearchListings :many
SELECT
  listings.id, listings.seller_id, listings.agent_id, listings.title, listings.description,
  listings.price, listings.currency, listings.category, listings.condition, listings.status,
  listings.signature_id, listings.created_at, listings.updated_at, listings.published_at, listings.sold_at
FROM listings
LEFT JOIN (
  SELECT listing_id, count(*) AS like_count FROM listing_likes GROUP BY listing_id
) lc ON lc.listing_id = listings.id
LEFT JOIN (
  SELECT listing_id, count(*) AS comment_count FROM listing_comments WHERE hidden_at IS NULL GROUP BY listing_id
) cc ON cc.listing_id = listings.id
LEFT JOIN users su ON su.id = listings.seller_id
WHERE ($1::listing_status IS NULL OR listings.status = $1::listing_status)
  AND ($2::uuid IS NULL OR listings.seller_id = $2::uuid)
  AND ($3::varchar IS NULL OR listings.category = $3::varchar)
  AND ($4::varchar IS NULL OR listings.condition = $4::varchar)
  AND ($5::integer IS NULL OR listings.price >= $5::integer)
  AND ($6::integer IS NULL OR listings.price <= $6::integer)
  AND (
    $7::text IS NULL
    OR listings.title ILIKE '%' || $7::text || '%'
    OR listings.description ILIKE '%' || $7::text || '%'
  )
  -- 「認証済みのみ」ファセット。Seal の正本＝出品者アカウントの人間認証(human_verified_at)で絞る
  -- （行為署名 signature_id ではない）。Route A: 認証済み出品者の出品は認証済みとして扱う。
  AND ($8::boolean IS NULL OR (su.human_verified_at IS NOT NULL) = $8::boolean)
ORDER BY
  CASE WHEN $9::text = 'priceAsc'  THEN listings.price END ASC,
  CASE WHEN $9::text = 'priceDesc' THEN listings.price END DESC,
  CASE WHEN $9::text = 'popular'   THEN COALESCE(lc.like_count, 0) END DESC,
  CASE WHEN $9::text = 'commented' THEN COALESCE(cc.comment_count, 0) END DESC,
  CASE WHEN $9::text = 'shuffle'   THEN md5(listings.id::text || COALESCE($10::text, '')) END ASC,
  listings.created_at DESC,
  listings.id DESC
LIMIT $12::integer OFFSET $11::integer
`

type SearchListingsParams struct {
	Status       *ListingStatus
	SellerID     *uuid.UUID
	Category     *string
	Condition    *string
	MinPrice     *int32
	MaxPrice     *int32
	Keyword      *string
	Signed       *bool
	Sort         *string
	Seed         *string
	ResultOffset int32
	ResultLimit  int32
}

// 有界(8フィルタ)の検索。各条件は narg がNULLなら無効化される（Query Builder不要）。
// ARCH-EXCEPTION(§peer): listings から social の listing_likes/listing_comments を read-only で LEFT JOIN する。
//
//	理由: popular(いいね順)/commented(コメント数順) は集計を ORDER BY に置く必要があり、ページング全体で
//	     安定させるには同一クエリ内で集計するしかない（後段の adapter 集計では駆動不可）。表示用カウントは
//	     従来どおり enrichWithCounts が担い、ここの集計は並び替え専用。denormalize 列の導入は write 経路の
//	     相互結合コストが大きいため見送り、読み取りJOINに限定する。
//
// 並び順は sort で選択（shuffle=seed付き決定的シャッフル / newest / popular / commented / priceAsc / priceDesc）。
// 末尾の id DESC で常に一意なタイブレーカーを持たせ、offset ページネーションと shuffle を安定させる。
func (q *Queries) SearchListings(ctx context.Context, arg SearchListingsParams) ([]Listing, error) {
	rows, err := q.db.Query(ctx, searchListings,
		arg.Status,
		arg.SellerID,
		arg.Category,
		arg.Condition,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Keyword,
		arg.Signed,
		arg.Sort,
		arg.Seed,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Listing{}
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Category,
			&i.Condition,
			&i.Status,
			&i.SignatureID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.SoldAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertListing = `-- name: UpsertListing :exec
INSERT INTO listings (
    id, seller_id, agent_id, title, description, price, currency, category, condition,
    status, signature_id, created_at, updated_at, published_at, sold_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    currency = EXCLUDED.currency,
    category = EXCLUDED.category,
    condition = EXCLUDED.condition,
    status = EXCLUDED.status,
    signature_id = EXCLUDED.signature_id,
    updated_at = EXCLUDED.updated_at,
    published_at = EXCLUDED.published_at,
    sold_at = EXCLUDED.sold_at
`

type UpsertListingParams struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	AgentID     *uuid.UUID
	Title       string
	Description string
	Price       int32
	Currency    string
	Category    string
	Condition   string
	Status      ListingStatus
	SignatureID *uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	SoldAt      pgtype.Timestamptz
}

func (q *Queries) UpsertListing(ctx context.Context, arg UpsertListingParams) error {
	_, err := q.db.Exec(ctx, upsertListing,
		arg.ID,
		arg.SellerID,
		arg.AgentID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.Category,
		arg.Condition,
		arg.Status,
		arg.SignatureID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.SoldAt,
	)
	return err
}
