// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertMcpToolCall = `-- name: InsertMcpToolCall :exec
INSERT INTO mcp_tool_calls (
    id, agent_id, user_id, tool_name, input_summary, output_summary, status, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertMcpToolCallParams struct {
	ID            uuid.UUID
	AgentID       *uuid.UUID
	UserID        uuid.UUID
	ToolName      string
	InputSummary  []byte
	OutputSummary []byte
	Status        McpToolCallStatus
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertMcpToolCall(ctx context.Context, arg InsertMcpToolCallParams) error {
	_, err := q.db.Exec(ctx, insertMcpToolCall,
		arg.ID,
		arg.AgentID,
		arg.UserID,
		arg.ToolName,
		arg.InputSummary,
		arg.OutputSummary,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}
