// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, order_id, sender_id, recipient_id, agent_id, body, status, created_at, hidden_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderID,
		&i.RecipientID,
		&i.AgentID,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.HiddenAt,
	)
	return i, err
}

const searchMessages = `-- name: SearchMessages :many
SELECT id, order_id, sender_id, recipient_id, agent_id, body, status, created_at, hidden_at FROM messages
WHERE ($1::uuid IS NULL OR order_id = $1::uuid)
  AND (
    $2::uuid IS NULL
    OR sender_id = $2::uuid
    OR recipient_id = $2::uuid
  )
  AND ($3::uuid IS NULL OR sender_id = $3::uuid)
  AND ($4::uuid IS NULL OR recipient_id = $4::uuid)
  AND ($5::message_status IS NULL OR status = $5::message_status)
ORDER BY created_at ASC
LIMIT $6::integer
`

type SearchMessagesParams struct {
	OrderID       *uuid.UUID
	ParticipantID *uuid.UUID
	SenderID      *uuid.UUID
	RecipientID   *uuid.UUID
	Status        *MessageStatus
	ResultLimit   int32
}

// 有界検索。participant_id は sender/recipient どちらか一致でフィルタ。
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.OrderID,
		arg.ParticipantID,
		arg.SenderID,
		arg.RecipientID,
		arg.Status,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SenderID,
			&i.RecipientID,
			&i.AgentID,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.HiddenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO messages (
    id, order_id, sender_id, recipient_id, agent_id, body, status, created_at, hidden_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    hidden_at = EXCLUDED.hidden_at
`

type UpsertMessageParams struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	SenderID    uuid.UUID
	RecipientID uuid.UUID
	AgentID     *uuid.UUID
	Body        string
	Status      MessageStatus
	CreatedAt   pgtype.Timestamptz
	HiddenAt    pgtype.Timestamptz
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.Exec(ctx, upsertMessage,
		arg.ID,
		arg.OrderID,
		arg.SenderID,
		arg.RecipientID,
		arg.AgentID,
		arg.Body,
		arg.Status,
		arg.CreatedAt,
		arg.HiddenAt,
	)
	return err
}
