// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentStatus string

const (
	AgentStatusACTIVE   AgentStatus = "ACTIVE"
	AgentStatusDISABLED AgentStatus = "DISABLED"
)

func (e *AgentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStatus(s)
	case string:
		*e = AgentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStatus: %T", src)
	}
	return nil
}

type NullAgentStatus struct {
	AgentStatus AgentStatus
	Valid       bool // Valid is true if AgentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStatus), nil
}

type AiActionType string

const (
	AiActionTypeCREATELISTINGDRAFT AiActionType = "CREATE_LISTING_DRAFT"
	AiActionTypePUBLISHLISTING     AiActionType = "PUBLISH_LISTING"
	AiActionTypeUPDATELISTING      AiActionType = "UPDATE_LISTING"
	AiActionTypeSEARCHLISTINGS     AiActionType = "SEARCH_LISTINGS"
	AiActionTypeCOMPARELISTINGS    AiActionType = "COMPARE_LISTINGS"
	AiActionTypeSUGGESTPRICE       AiActionType = "SUGGEST_PRICE"
	AiActionTypeSUGGESTMESSAGE     AiActionType = "SUGGEST_MESSAGE"
	AiActionTypeSENDMESSAGE        AiActionType = "SEND_MESSAGE"
	AiActionTypePREPAREPURCHASE    AiActionType = "PREPARE_PURCHASE"
	AiActionTypePURCHASEITEM       AiActionType = "PURCHASE_ITEM"
	AiActionTypeSUGGESTREVIEW      AiActionType = "SUGGEST_REVIEW"
	AiActionTypeSUBMITREVIEW       AiActionType = "SUBMIT_REVIEW"
)

func (e *AiActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiActionType(s)
	case string:
		*e = AiActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for AiActionType: %T", src)
	}
	return nil
}

type NullAiActionType struct {
	AiActionType AiActionType
	Valid        bool // Valid is true if AiActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiActionType) Scan(value interface{}) error {
	if value == nil {
		ns.AiActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiActionType), nil
}

type ListingStatus string

const (
	ListingStatusDRAFT     ListingStatus = "DRAFT"
	ListingStatusPUBLISHED ListingStatus = "PUBLISHED"
	ListingStatusSOLD      ListingStatus = "SOLD"
	ListingStatusHIDDEN    ListingStatus = "HIDDEN"
)

func (e *ListingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingStatus(s)
	case string:
		*e = ListingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingStatus: %T", src)
	}
	return nil
}

type NullListingStatus struct {
	ListingStatus ListingStatus
	Valid         bool // Valid is true if ListingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingStatus), nil
}

type McpToolCallStatus string

const (
	McpToolCallStatusSTARTED                McpToolCallStatus = "STARTED"
	McpToolCallStatusSUCCEEDED              McpToolCallStatus = "SUCCEEDED"
	McpToolCallStatusFAILED                 McpToolCallStatus = "FAILED"
	McpToolCallStatusREQUIRESHUMANSIGNATURE McpToolCallStatus = "REQUIRES_HUMAN_SIGNATURE"
	McpToolCallStatusREQUIRESCONFIRMATION   McpToolCallStatus = "REQUIRES_CONFIRMATION"
)

func (e *McpToolCallStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = McpToolCallStatus(s)
	case string:
		*e = McpToolCallStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for McpToolCallStatus: %T", src)
	}
	return nil
}

type NullMcpToolCallStatus struct {
	McpToolCallStatus McpToolCallStatus
	Valid             bool // Valid is true if McpToolCallStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMcpToolCallStatus) Scan(value interface{}) error {
	if value == nil {
		ns.McpToolCallStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.McpToolCallStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMcpToolCallStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.McpToolCallStatus), nil
}

type MessageStatus string

const (
	MessageStatusSENT   MessageStatus = "SENT"
	MessageStatusHIDDEN MessageStatus = "HIDDEN"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus
	Valid         bool // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

type OrderStatus string

const (
	OrderStatusPAID      OrderStatus = "PAID"
	OrderStatusSHIPPED   OrderStatus = "SHIPPED"
	OrderStatusRECEIVED  OrderStatus = "RECEIVED"
	OrderStatusCOMPLETED OrderStatus = "COMPLETED"
	OrderStatusCANCELED  OrderStatus = "CANCELED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type ReviewStatus string

const (
	ReviewStatusDRAFT     ReviewStatus = "DRAFT"
	ReviewStatusSUBMITTED ReviewStatus = "SUBMITTED"
	ReviewStatusHIDDEN    ReviewStatus = "HIDDEN"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus
	Valid        bool // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type SignatureFormat string

const (
	SignatureFormatJWS SignatureFormat = "JWS"
)

func (e *SignatureFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignatureFormat(s)
	case string:
		*e = SignatureFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for SignatureFormat: %T", src)
	}
	return nil
}

type NullSignatureFormat struct {
	SignatureFormat SignatureFormat
	Valid           bool // Valid is true if SignatureFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignatureFormat) Scan(value interface{}) error {
	if value == nil {
		ns.SignatureFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignatureFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignatureFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignatureFormat), nil
}

type SignatureStatus string

const (
	SignatureStatusVALID   SignatureStatus = "VALID"
	SignatureStatusREVOKED SignatureStatus = "REVOKED"
)

func (e *SignatureStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignatureStatus(s)
	case string:
		*e = SignatureStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SignatureStatus: %T", src)
	}
	return nil
}

type NullSignatureStatus struct {
	SignatureStatus SignatureStatus
	Valid           bool // Valid is true if SignatureStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignatureStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SignatureStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignatureStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignatureStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignatureStatus), nil
}

type UserStatus string

const (
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Agent struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Status    AgentStatus
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AiActionLog struct {
	ID            uuid.UUID
	AgentID       *uuid.UUID
	UserID        uuid.UUID
	ActionType    AiActionType
	ResourceType  *string
	ResourceID    *uuid.UUID
	Model         *string
	PromptSummary []byte
	ResultSummary []byte
	CreatedAt     pgtype.Timestamptz
}

type AuthIdentity struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderSubject string
	CreatedAt       pgtype.Timestamptz
}

type HumanSignature struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	ActionType            string
	ResourceType          string
	ResourceID            uuid.UUID
	PayloadHash           string
	SignatureFormat       SignatureFormat
	SignatureValue        string
	WorldIDVerificationID uuid.UUID
	Status                SignatureStatus
	SignedAt              pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
}

type Listing struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	AgentID     *uuid.UUID
	Title       string
	Description string
	Price       int32
	Currency    string
	Category    string
	Condition   string
	Status      ListingStatus
	SignatureID *uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	SoldAt      pgtype.Timestamptz
}

type ListingImage struct {
	ID        uuid.UUID
	ListingID uuid.UUID
	Url       string
	ImageHash string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

type ListingLike struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type McpToolCall struct {
	ID            uuid.UUID
	AgentID       *uuid.UUID
	UserID        uuid.UUID
	ToolName      string
	InputSummary  []byte
	OutputSummary []byte
	Status        McpToolCallStatus
	CreatedAt     pgtype.Timestamptz
}

type Message struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	SenderID    uuid.UUID
	RecipientID uuid.UUID
	AgentID     *uuid.UUID
	Body        string
	Status      MessageStatus
	CreatedAt   pgtype.Timestamptz
	HiddenAt    pgtype.Timestamptz
}

type Order struct {
	ID          uuid.UUID
	ListingID   uuid.UUID
	BuyerID     uuid.UUID
	SellerID    uuid.UUID
	Status      OrderStatus
	Price       int32
	Currency    string
	CreatedAt   pgtype.Timestamptz
	PaidAt      pgtype.Timestamptz
	ShippedAt   pgtype.Timestamptz
	ReceivedAt  pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	CanceledAt  pgtype.Timestamptz
}

type Review struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ReviewerID  uuid.UUID
	RevieweeID  uuid.UUID
	AgentID     *uuid.UUID
	Rating      int32
	Comment     string
	Status      ReviewStatus
	SignatureID *uuid.UUID
	CreatedAt   pgtype.Timestamptz
	SubmittedAt pgtype.Timestamptz
	HiddenAt    pgtype.Timestamptz
}

type SellerLike struct {
	UserID    uuid.UUID
	SellerID  uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID              uuid.UUID
	DisplayName     string
	Email           *string
	AvatarUrl       *string
	Status          UserStatus
	HumanVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type WorldIDVerification struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Action            string
	NullifierHash     string
	VerificationLevel string
	SignalHash        *string
	Environment       string
	VerifiedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}
