// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, listing_id, buyer_id, seller_id, status, price, currency, created_at, paid_at, shipped_at, received_at, completed_at, canceled_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.Price,
		&i.Currency,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.CanceledAt,
	)
	return i, err
}

const getOrderByListingID = `-- name: GetOrderByListingID :one
SELECT id, listing_id, buyer_id, seller_id, status, price, currency, created_at, paid_at, shipped_at, received_at, completed_at, canceled_at FROM orders WHERE listing_id = $1
`

func (q *Queries) GetOrderByListingID(ctx context.Context, listingID uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByListingID, listingID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.Price,
		&i.Currency,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.CanceledAt,
	)
	return i, err
}

const searchOrders = `-- name: SearchOrders :many
SELECT id, listing_id, buyer_id, seller_id, status, price, currency, created_at, paid_at, shipped_at, received_at, completed_at, canceled_at FROM orders
WHERE (
    $1::uuid IS NULL
    OR buyer_id = $1::uuid
    OR seller_id = $1::uuid
  )
  AND ($2::uuid IS NULL OR buyer_id = $2::uuid)
  AND ($3::uuid IS NULL OR seller_id = $3::uuid)
  AND ($4::order_status IS NULL OR status = $4::order_status)
ORDER BY created_at ASC
LIMIT $5::integer
`

type SearchOrdersParams struct {
	ParticipantID *uuid.UUID
	BuyerID       *uuid.UUID
	SellerID      *uuid.UUID
	Status        *OrderStatus
	ResultLimit   int32
}

// 有界検索。participant_id は buyer/seller どちらか一致でフィルタ。
func (q *Queries) SearchOrders(ctx context.Context, arg SearchOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, searchOrders,
		arg.ParticipantID,
		arg.BuyerID,
		arg.SellerID,
		arg.Status,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.Status,
			&i.Price,
			&i.Currency,
			&i.CreatedAt,
			&i.PaidAt,
			&i.ShippedAt,
			&i.ReceivedAt,
			&i.CompletedAt,
			&i.CanceledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrder = `-- name: UpsertOrder :exec
INSERT INTO orders (
    id, listing_id, buyer_id, seller_id, status, price, currency,
    created_at, paid_at, shipped_at, received_at, completed_at, canceled_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    shipped_at = EXCLUDED.shipped_at,
    received_at = EXCLUDED.received_at,
    completed_at = EXCLUDED.completed_at,
    canceled_at = EXCLUDED.canceled_at
`

type UpsertOrderParams struct {
	ID          uuid.UUID
	ListingID   uuid.UUID
	BuyerID     uuid.UUID
	SellerID    uuid.UUID
	Status      OrderStatus
	Price       int32
	Currency    string
	CreatedAt   pgtype.Timestamptz
	PaidAt      pgtype.Timestamptz
	ShippedAt   pgtype.Timestamptz
	ReceivedAt  pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	CanceledAt  pgtype.Timestamptz
}

func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) error {
	_, err := q.db.Exec(ctx, upsertOrder,
		arg.ID,
		arg.ListingID,
		arg.BuyerID,
		arg.SellerID,
		arg.Status,
		arg.Price,
		arg.Currency,
		arg.CreatedAt,
		arg.PaidAt,
		arg.ShippedAt,
		arg.ReceivedAt,
		arg.CompletedAt,
		arg.CanceledAt,
	)
	return err
}
