// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findSubmittedReviewByOrderReviewer = `-- name: FindSubmittedReviewByOrderReviewer :one
SELECT id, order_id, reviewer_id, reviewee_id, agent_id, rating, comment, status, signature_id, created_at, submitted_at, hidden_at FROM reviews
WHERE order_id = $1 AND reviewer_id = $2 AND status = 'SUBMITTED'
LIMIT 1
`

type FindSubmittedReviewByOrderReviewerParams struct {
	OrderID    uuid.UUID
	ReviewerID uuid.UUID
}

func (q *Queries) FindSubmittedReviewByOrderReviewer(ctx context.Context, arg FindSubmittedReviewByOrderReviewerParams) (Review, error) {
	row := q.db.QueryRow(ctx, findSubmittedReviewByOrderReviewer, arg.OrderID, arg.ReviewerID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.AgentID,
		&i.Rating,
		&i.Comment,
		&i.Status,
		&i.SignatureID,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.HiddenAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, order_id, reviewer_id, reviewee_id, agent_id, rating, comment, status, signature_id, created_at, submitted_at, hidden_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id uuid.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.AgentID,
		&i.Rating,
		&i.Comment,
		&i.Status,
		&i.SignatureID,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.HiddenAt,
	)
	return i, err
}

const searchReviews = `-- name: SearchReviews :many
SELECT id, order_id, reviewer_id, reviewee_id, agent_id, rating, comment, status, signature_id, created_at, submitted_at, hidden_at FROM reviews
WHERE ($1::uuid IS NULL OR order_id = $1::uuid)
  AND ($2::uuid IS NULL OR reviewer_id = $2::uuid)
  AND ($3::uuid IS NULL OR reviewee_id = $3::uuid)
  AND ($4::review_status IS NULL OR status = $4::review_status)
ORDER BY created_at ASC
LIMIT $5::integer
`

type SearchReviewsParams struct {
	OrderID     *uuid.UUID
	ReviewerID  *uuid.UUID
	RevieweeID  *uuid.UUID
	Status      *ReviewStatus
	ResultLimit int32
}

func (q *Queries) SearchReviews(ctx context.Context, arg SearchReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, searchReviews,
		arg.OrderID,
		arg.ReviewerID,
		arg.RevieweeID,
		arg.Status,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ReviewerID,
			&i.RevieweeID,
			&i.AgentID,
			&i.Rating,
			&i.Comment,
			&i.Status,
			&i.SignatureID,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.HiddenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReview = `-- name: UpsertReview :exec
INSERT INTO reviews (
    id, order_id, reviewer_id, reviewee_id, agent_id, rating, comment,
    status, signature_id, created_at, submitted_at, hidden_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (id) DO UPDATE SET
    rating = EXCLUDED.rating,
    comment = EXCLUDED.comment,
    status = EXCLUDED.status,
    signature_id = EXCLUDED.signature_id,
    submitted_at = EXCLUDED.submitted_at,
    hidden_at = EXCLUDED.hidden_at
`

type UpsertReviewParams struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ReviewerID  uuid.UUID
	RevieweeID  uuid.UUID
	AgentID     *uuid.UUID
	Rating      int32
	Comment     string
	Status      ReviewStatus
	SignatureID *uuid.UUID
	CreatedAt   pgtype.Timestamptz
	SubmittedAt pgtype.Timestamptz
	HiddenAt    pgtype.Timestamptz
}

func (q *Queries) UpsertReview(ctx context.Context, arg UpsertReviewParams) error {
	_, err := q.db.Exec(ctx, upsertReview,
		arg.ID,
		arg.OrderID,
		arg.ReviewerID,
		arg.RevieweeID,
		arg.AgentID,
		arg.Rating,
		arg.Comment,
		arg.Status,
		arg.SignatureID,
		arg.CreatedAt,
		arg.SubmittedAt,
		arg.HiddenAt,
	)
	return err
}
