// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signatures.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWorldIdVerificationsByUserAction = `-- name: CountWorldIdVerificationsByUserAction :one
SELECT count(*) FROM world_id_verifications WHERE user_id = $1 AND action = $2
`

type CountWorldIdVerificationsByUserActionParams struct {
	UserID uuid.UUID
	Action string
}

func (q *Queries) CountWorldIdVerificationsByUserAction(ctx context.Context, arg CountWorldIdVerificationsByUserActionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorldIdVerificationsByUserAction, arg.UserID, arg.Action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findValidHumanSignature = `-- name: FindValidHumanSignature :one
SELECT id, user_id, action_type, resource_type, resource_id, payload_hash, signature_format, signature_value, world_id_verification_id, status, signed_at, revoked_at FROM human_signatures
WHERE action_type = $1
  AND resource_type = $2
  AND resource_id = $3
  AND payload_hash = $4
  AND status = 'VALID'
LIMIT 1
`

type FindValidHumanSignatureParams struct {
	ActionType   string
	ResourceType string
	ResourceID   uuid.UUID
	PayloadHash  string
}

func (q *Queries) FindValidHumanSignature(ctx context.Context, arg FindValidHumanSignatureParams) (HumanSignature, error) {
	row := q.db.QueryRow(ctx, findValidHumanSignature,
		arg.ActionType,
		arg.ResourceType,
		arg.ResourceID,
		arg.PayloadHash,
	)
	var i HumanSignature
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActionType,
		&i.ResourceType,
		&i.ResourceID,
		&i.PayloadHash,
		&i.SignatureFormat,
		&i.SignatureValue,
		&i.WorldIDVerificationID,
		&i.Status,
		&i.SignedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertHumanSignature = `-- name: InsertHumanSignature :exec
INSERT INTO human_signatures (
    id, user_id, action_type, resource_type, resource_id, payload_hash,
    signature_format, signature_value, world_id_verification_id, status, signed_at, revoked_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    revoked_at = EXCLUDED.revoked_at
`

type InsertHumanSignatureParams struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	ActionType            string
	ResourceType          string
	ResourceID            uuid.UUID
	PayloadHash           string
	SignatureFormat       SignatureFormat
	SignatureValue        string
	WorldIDVerificationID uuid.UUID
	Status                SignatureStatus
	SignedAt              pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
}

func (q *Queries) InsertHumanSignature(ctx context.Context, arg InsertHumanSignatureParams) error {
	_, err := q.db.Exec(ctx, insertHumanSignature,
		arg.ID,
		arg.UserID,
		arg.ActionType,
		arg.ResourceType,
		arg.ResourceID,
		arg.PayloadHash,
		arg.SignatureFormat,
		arg.SignatureValue,
		arg.WorldIDVerificationID,
		arg.Status,
		arg.SignedAt,
		arg.RevokedAt,
	)
	return err
}

const insertWorldIdVerification = `-- name: InsertWorldIdVerification :exec
INSERT INTO world_id_verifications (
    id, user_id, action, nullifier_hash, verification_level, signal_hash, environment, verified_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertWorldIdVerificationParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Action            string
	NullifierHash     string
	VerificationLevel string
	SignalHash        *string
	Environment       string
	VerifiedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertWorldIdVerification(ctx context.Context, arg InsertWorldIdVerificationParams) error {
	_, err := q.db.Exec(ctx, insertWorldIdVerification,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.NullifierHash,
		arg.VerificationLevel,
		arg.SignalHash,
		arg.Environment,
		arg.VerifiedAt,
		arg.CreatedAt,
	)
	return err
}
