// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByListing = `-- name: CountCommentsByListing :one
SELECT count(*) FROM listing_comments WHERE listing_id = $1 AND hidden_at IS NULL
`

func (q *Queries) CountCommentsByListing(ctx context.Context, listingID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByListing, listingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommentsByListingIDs = `-- name: CountCommentsByListingIDs :many
SELECT listing_id, count(*) AS comment_count
FROM listing_comments
WHERE hidden_at IS NULL AND listing_id = ANY($1::uuid[])
GROUP BY listing_id
`

type CountCommentsByListingIDsRow struct {
	ListingID    uuid.UUID
	CommentCount int64
}

func (q *Queries) CountCommentsByListingIDs(ctx context.Context, listingIds []uuid.UUID) ([]CountCommentsByListingIDsRow, error) {
	rows, err := q.db.Query(ctx, countCommentsByListingIDs, listingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCommentsByListingIDsRow{}
	for rows.Next() {
		var i CountCommentsByListingIDsRow
		if err := rows.Scan(&i.ListingID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLikesByListingIDs = `-- name: CountLikesByListingIDs :many
SELECT listing_id, count(*) AS like_count
FROM listing_likes
WHERE listing_id = ANY($1::uuid[])
GROUP BY listing_id
`

type CountLikesByListingIDsRow struct {
	ListingID uuid.UUID
	LikeCount int64
}

// フィード用バッチ集計。指定id群のいいね数をまとめて返す（0件のidは行が出ない＝呼び出し側で0補完）。
func (q *Queries) CountLikesByListingIDs(ctx context.Context, listingIds []uuid.UUID) ([]CountLikesByListingIDsRow, error) {
	rows, err := q.db.Query(ctx, countLikesByListingIDs, listingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLikesByListingIDsRow{}
	for rows.Next() {
		var i CountLikesByListingIDsRow
		if err := rows.Scan(&i.ListingID, &i.LikeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countListingLikes = `-- name: CountListingLikes :one
SELECT count(*) FROM listing_likes WHERE listing_id = $1
`

func (q *Queries) CountListingLikes(ctx context.Context, listingID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countListingLikes, listingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSellerLikes = `-- name: CountSellerLikes :one
SELECT count(*) FROM seller_likes WHERE seller_id = $1
`

func (q *Queries) CountSellerLikes(ctx context.Context, sellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerLikes, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followSeller = `-- name: FollowSeller :exec
INSERT INTO seller_follows (follower_id, seller_id) VALUES ($1, $2)
ON CONFLICT (follower_id, seller_id) DO NOTHING
`

type FollowSellerParams struct {
	FollowerID uuid.UUID
	SellerID   uuid.UUID
}

// 出品者のフォロー（私的）。冪等。
func (q *Queries) FollowSeller(ctx context.Context, arg FollowSellerParams) error {
	_, err := q.db.Exec(ctx, followSeller, arg.FollowerID, arg.SellerID)
	return err
}

const getSellerProfile = `-- name: GetSellerProfile :one
SELECT display_name, avatar_url, (human_verified_at IS NOT NULL)::boolean AS human_verified
FROM users WHERE id = $1
`

type GetSellerProfileRow struct {
	DisplayName   string
	AvatarUrl     *string
	HumanVerified bool
}

func (q *Queries) GetSellerProfile(ctx context.Context, id uuid.UUID) (GetSellerProfileRow, error) {
	row := q.db.QueryRow(ctx, getSellerProfile, id)
	var i GetSellerProfileRow
	err := row.Scan(&i.DisplayName, &i.AvatarUrl, &i.HumanVerified)
	return i, err
}

const getSellerRating = `-- name: GetSellerRating :one
SELECT COALESCE(AVG(rating::float8), 0)::float8 AS rating, count(*) AS review_count
FROM reviews WHERE reviewee_id = $1 AND status = 'SUBMITTED'
`

type GetSellerRatingRow struct {
	Rating      float64
	ReviewCount int64
}

// SUBMITTED(World ID署名済み)のみ集計。レビュー0件は review_count=0 で表し、
// AVG の NULL を COALESCE(...,0) で潰す（float64非null）。0件→Average=nil の判定は repo 側で行う。
func (q *Queries) GetSellerRating(ctx context.Context, revieweeID uuid.UUID) (GetSellerRatingRow, error) {
	row := q.db.QueryRow(ctx, getSellerRating, revieweeID)
	var i GetSellerRatingRow
	err := row.Scan(&i.Rating, &i.ReviewCount)
	return i, err
}

const insertListingComment = `-- name: InsertListingComment :exec
INSERT INTO listing_comments (id, listing_id, author_id, body) VALUES ($1, $2, $3, $4)
`

type InsertListingCommentParams struct {
	ID        uuid.UUID
	ListingID uuid.UUID
	AuthorID  uuid.UUID
	Body      string
}

func (q *Queries) InsertListingComment(ctx context.Context, arg InsertListingCommentParams) error {
	_, err := q.db.Exec(ctx, insertListingComment,
		arg.ID,
		arg.ListingID,
		arg.AuthorID,
		arg.Body,
	)
	return err
}

const isFollowingSeller = `-- name: IsFollowingSeller :one
SELECT EXISTS (SELECT 1 FROM seller_follows WHERE follower_id = $1 AND seller_id = $2)
`

type IsFollowingSellerParams struct {
	FollowerID uuid.UUID
	SellerID   uuid.UUID
}

func (q *Queries) IsFollowingSeller(ctx context.Context, arg IsFollowingSellerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingSeller, arg.FollowerID, arg.SellerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isListingLiked = `-- name: IsListingLiked :one
SELECT EXISTS (SELECT 1 FROM listing_likes WHERE user_id = $1 AND listing_id = $2)
`

type IsListingLikedParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) IsListingLiked(ctx context.Context, arg IsListingLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isListingLiked, arg.UserID, arg.ListingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isListingSaved = `-- name: IsListingSaved :one
SELECT EXISTS (SELECT 1 FROM listing_saves WHERE user_id = $1 AND listing_id = $2)
`

type IsListingSavedParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) IsListingSaved(ctx context.Context, arg IsListingSavedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isListingSaved, arg.UserID, arg.ListingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isSellerLiked = `-- name: IsSellerLiked :one
SELECT EXISTS (SELECT 1 FROM seller_likes WHERE user_id = $1 AND seller_id = $2)
`

type IsSellerLikedParams struct {
	UserID   uuid.UUID
	SellerID uuid.UUID
}

func (q *Queries) IsSellerLiked(ctx context.Context, arg IsSellerLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSellerLiked, arg.UserID, arg.SellerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likeListing = `-- name: LikeListing :exec
INSERT INTO listing_likes (user_id, listing_id) VALUES ($1, $2)
ON CONFLICT (user_id, listing_id) DO NOTHING
`

type LikeListingParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) LikeListing(ctx context.Context, arg LikeListingParams) error {
	_, err := q.db.Exec(ctx, likeListing, arg.UserID, arg.ListingID)
	return err
}

const likeSeller = `-- name: LikeSeller :exec
INSERT INTO seller_likes (user_id, seller_id) VALUES ($1, $2)
ON CONFLICT (user_id, seller_id) DO NOTHING
`

type LikeSellerParams struct {
	UserID   uuid.UUID
	SellerID uuid.UUID
}

func (q *Queries) LikeSeller(ctx context.Context, arg LikeSellerParams) error {
	_, err := q.db.Exec(ctx, likeSeller, arg.UserID, arg.SellerID)
	return err
}

const listCommentsByListing = `-- name: ListCommentsByListing :many
SELECT c.id, c.listing_id, c.author_id, c.body, c.created_at,
       u.display_name AS author_display_name,
       (u.human_verified_at IS NOT NULL)::boolean AS author_human_verified
FROM listing_comments c
JOIN users u ON u.id = c.author_id
WHERE c.listing_id = $1 AND c.hidden_at IS NULL
ORDER BY c.created_at DESC
LIMIT $3::integer OFFSET $2::integer
`

type ListCommentsByListingParams struct {
	ListingID    uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

type ListCommentsByListingRow struct {
	ID                  uuid.UUID
	ListingID           uuid.UUID
	AuthorID            uuid.UUID
	Body                string
	CreatedAt           pgtype.Timestamptz
	AuthorDisplayName   string
	AuthorHumanVerified bool
}

// 公開コメントを新しい順に。著者の表示名/本人認証バッジを users から join。
func (q *Queries) ListCommentsByListing(ctx context.Context, arg ListCommentsByListingParams) ([]ListCommentsByListingRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByListing, arg.ListingID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByListingRow{}
	for rows.Next() {
		var i ListCommentsByListingRow
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorDisplayName,
			&i.AuthorHumanVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowedSellerIDs = `-- name: ListFollowedSellerIDs :many
SELECT seller_id FROM seller_follows
WHERE follower_id = $1
ORDER BY created_at DESC
LIMIT $3::integer OFFSET $2::integer
`

type ListFollowedSellerIDsParams struct {
	FollowerID   uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListFollowedSellerIDs(ctx context.Context, arg ListFollowedSellerIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFollowedSellerIDs, arg.FollowerID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var seller_id uuid.UUID
		if err := rows.Scan(&seller_id); err != nil {
			return nil, err
		}
		items = append(items, seller_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedListingIDs = `-- name: ListLikedListingIDs :many
SELECT listing_id FROM listing_likes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::integer OFFSET $2::integer
`

type ListLikedListingIDsParams struct {
	UserID       uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListLikedListingIDs(ctx context.Context, arg ListLikedListingIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLikedListingIDs, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var listing_id uuid.UUID
		if err := rows.Scan(&listing_id); err != nil {
			return nil, err
		}
		items = append(items, listing_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedSellerIDs = `-- name: ListLikedSellerIDs :many
SELECT seller_id FROM seller_likes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::integer OFFSET $2::integer
`

type ListLikedSellerIDsParams struct {
	UserID       uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListLikedSellerIDs(ctx context.Context, arg ListLikedSellerIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLikedSellerIDs, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var seller_id uuid.UUID
		if err := rows.Scan(&seller_id); err != nil {
			return nil, err
		}
		items = append(items, seller_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedListingIDs = `-- name: ListSavedListingIDs :many
SELECT listing_id FROM listing_saves
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::integer OFFSET $2::integer
`

type ListSavedListingIDsParams struct {
	UserID       uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListSavedListingIDs(ctx context.Context, arg ListSavedListingIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSavedListingIDs, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var listing_id uuid.UUID
		if err := rows.Scan(&listing_id); err != nil {
			return nil, err
		}
		items = append(items, listing_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveListing = `-- name: SaveListing :exec
INSERT INTO listing_saves (user_id, listing_id) VALUES ($1, $2)
ON CONFLICT (user_id, listing_id) DO NOTHING
`

type SaveListingParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

// 商品の保存（私的ウォッチリスト）。冪等。
func (q *Queries) SaveListing(ctx context.Context, arg SaveListingParams) error {
	_, err := q.db.Exec(ctx, saveListing, arg.UserID, arg.ListingID)
	return err
}

const unfollowSeller = `-- name: UnfollowSeller :exec
DELETE FROM seller_follows WHERE follower_id = $1 AND seller_id = $2
`

type UnfollowSellerParams struct {
	FollowerID uuid.UUID
	SellerID   uuid.UUID
}

func (q *Queries) UnfollowSeller(ctx context.Context, arg UnfollowSellerParams) error {
	_, err := q.db.Exec(ctx, unfollowSeller, arg.FollowerID, arg.SellerID)
	return err
}

const unlikeListing = `-- name: UnlikeListing :exec
DELETE FROM listing_likes WHERE user_id = $1 AND listing_id = $2
`

type UnlikeListingParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) UnlikeListing(ctx context.Context, arg UnlikeListingParams) error {
	_, err := q.db.Exec(ctx, unlikeListing, arg.UserID, arg.ListingID)
	return err
}

const unlikeSeller = `-- name: UnlikeSeller :exec
DELETE FROM seller_likes WHERE user_id = $1 AND seller_id = $2
`

type UnlikeSellerParams struct {
	UserID   uuid.UUID
	SellerID uuid.UUID
}

func (q *Queries) UnlikeSeller(ctx context.Context, arg UnlikeSellerParams) error {
	_, err := q.db.Exec(ctx, unlikeSeller, arg.UserID, arg.SellerID)
	return err
}

const unsaveListing = `-- name: UnsaveListing :exec
DELETE FROM listing_saves WHERE user_id = $1 AND listing_id = $2
`

type UnsaveListingParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) UnsaveListing(ctx context.Context, arg UnsaveListingParams) error {
	_, err := q.db.Exec(ctx, unsaveListing, arg.UserID, arg.ListingID)
	return err
}
