// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countListingLikes = `-- name: CountListingLikes :one
SELECT count(*) FROM listing_likes WHERE listing_id = $1
`

func (q *Queries) CountListingLikes(ctx context.Context, listingID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countListingLikes, listingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSellerLikes = `-- name: CountSellerLikes :one
SELECT count(*) FROM seller_likes WHERE seller_id = $1
`

func (q *Queries) CountSellerLikes(ctx context.Context, sellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerLikes, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSellerProfile = `-- name: GetSellerProfile :one
SELECT display_name, avatar_url, (human_verified_at IS NOT NULL)::boolean AS human_verified
FROM users WHERE id = $1
`

type GetSellerProfileRow struct {
	DisplayName   string
	AvatarUrl     *string
	HumanVerified bool
}

func (q *Queries) GetSellerProfile(ctx context.Context, id uuid.UUID) (GetSellerProfileRow, error) {
	row := q.db.QueryRow(ctx, getSellerProfile, id)
	var i GetSellerProfileRow
	err := row.Scan(&i.DisplayName, &i.AvatarUrl, &i.HumanVerified)
	return i, err
}

const getSellerRating = `-- name: GetSellerRating :one
SELECT COALESCE(AVG(rating::float8), 0)::float8 AS rating, count(*) AS review_count
FROM reviews WHERE reviewee_id = $1 AND status = 'SUBMITTED'
`

type GetSellerRatingRow struct {
	Rating      float64
	ReviewCount int64
}

// SUBMITTED(World ID署名済み)のみ集計。レビュー0件は review_count=0 で表し、
// AVG の NULL を COALESCE(...,0) で潰す（float64非null）。0件→Average=nil の判定は repo 側で行う。
func (q *Queries) GetSellerRating(ctx context.Context, revieweeID uuid.UUID) (GetSellerRatingRow, error) {
	row := q.db.QueryRow(ctx, getSellerRating, revieweeID)
	var i GetSellerRatingRow
	err := row.Scan(&i.Rating, &i.ReviewCount)
	return i, err
}

const isListingLiked = `-- name: IsListingLiked :one
SELECT EXISTS (SELECT 1 FROM listing_likes WHERE user_id = $1 AND listing_id = $2)
`

type IsListingLikedParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) IsListingLiked(ctx context.Context, arg IsListingLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isListingLiked, arg.UserID, arg.ListingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isSellerLiked = `-- name: IsSellerLiked :one
SELECT EXISTS (SELECT 1 FROM seller_likes WHERE user_id = $1 AND seller_id = $2)
`

type IsSellerLikedParams struct {
	UserID   uuid.UUID
	SellerID uuid.UUID
}

func (q *Queries) IsSellerLiked(ctx context.Context, arg IsSellerLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSellerLiked, arg.UserID, arg.SellerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likeListing = `-- name: LikeListing :exec
INSERT INTO listing_likes (user_id, listing_id) VALUES ($1, $2)
ON CONFLICT (user_id, listing_id) DO NOTHING
`

type LikeListingParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) LikeListing(ctx context.Context, arg LikeListingParams) error {
	_, err := q.db.Exec(ctx, likeListing, arg.UserID, arg.ListingID)
	return err
}

const likeSeller = `-- name: LikeSeller :exec
INSERT INTO seller_likes (user_id, seller_id) VALUES ($1, $2)
ON CONFLICT (user_id, seller_id) DO NOTHING
`

type LikeSellerParams struct {
	UserID   uuid.UUID
	SellerID uuid.UUID
}

func (q *Queries) LikeSeller(ctx context.Context, arg LikeSellerParams) error {
	_, err := q.db.Exec(ctx, likeSeller, arg.UserID, arg.SellerID)
	return err
}

const listLikedListingIDs = `-- name: ListLikedListingIDs :many
SELECT listing_id FROM listing_likes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::integer OFFSET $2::integer
`

type ListLikedListingIDsParams struct {
	UserID       uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListLikedListingIDs(ctx context.Context, arg ListLikedListingIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLikedListingIDs, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var listing_id uuid.UUID
		if err := rows.Scan(&listing_id); err != nil {
			return nil, err
		}
		items = append(items, listing_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedSellerIDs = `-- name: ListLikedSellerIDs :many
SELECT seller_id FROM seller_likes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::integer OFFSET $2::integer
`

type ListLikedSellerIDsParams struct {
	UserID       uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListLikedSellerIDs(ctx context.Context, arg ListLikedSellerIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLikedSellerIDs, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var seller_id uuid.UUID
		if err := rows.Scan(&seller_id); err != nil {
			return nil, err
		}
		items = append(items, seller_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlikeListing = `-- name: UnlikeListing :exec
DELETE FROM listing_likes WHERE user_id = $1 AND listing_id = $2
`

type UnlikeListingParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) UnlikeListing(ctx context.Context, arg UnlikeListingParams) error {
	_, err := q.db.Exec(ctx, unlikeListing, arg.UserID, arg.ListingID)
	return err
}

const unlikeSeller = `-- name: UnlikeSeller :exec
DELETE FROM seller_likes WHERE user_id = $1 AND seller_id = $2
`

type UnlikeSellerParams struct {
	UserID   uuid.UUID
	SellerID uuid.UUID
}

func (q *Queries) UnlikeSeller(ctx context.Context, arg UnlikeSellerParams) error {
	_, err := q.db.Exec(ctx, unlikeSeller, arg.UserID, arg.SellerID)
	return err
}
