// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ping = `-- name: Ping :one
SELECT now()::timestamptz AS now
`

func (q *Queries) Ping(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, ping)
	var now pgtype.Timestamptz
	err := row.Scan(&now)
	return now, err
}
