// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, display_name, email, avatar_url, status, human_verified_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.Status,
		&i.HumanVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, email, avatar_url, status, human_verified_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.Status,
		&i.HumanVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHumanVerifiedByIDs = `-- name: ListHumanVerifiedByIDs :many
SELECT id, (human_verified_at IS NOT NULL)::boolean AS human_verified
FROM users
WHERE id = ANY($1::uuid[])
`

type ListHumanVerifiedByIDsRow struct {
	ID            uuid.UUID
	HumanVerified bool
}

// 指定ユーザーの人間認証状態をバッチ取得する。出品カード等で出品者の認証マーク(Seal)を
// 出すために listings 側 enrich から呼ばれる（Seal の正本はアカウント認証＝human_verified_at）。
func (q *Queries) ListHumanVerifiedByIDs(ctx context.Context, userIds []uuid.UUID) ([]ListHumanVerifiedByIDsRow, error) {
	rows, err := q.db.Query(ctx, listHumanVerifiedByIDs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHumanVerifiedByIDsRow{}
	for rows.Next() {
		var i ListHumanVerifiedByIDsRow
		if err := rows.Scan(&i.ID, &i.HumanVerified); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserHumanVerified = `-- name: MarkUserHumanVerified :exec
UPDATE users SET human_verified_at = $2, updated_at = $3 WHERE id = $1
`

type MarkUserHumanVerifiedParams struct {
	ID              uuid.UUID
	HumanVerifiedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) MarkUserHumanVerified(ctx context.Context, arg MarkUserHumanVerifiedParams) error {
	_, err := q.db.Exec(ctx, markUserHumanVerified, arg.ID, arg.HumanVerifiedAt, arg.UpdatedAt)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, display_name, email, avatar_url, status, human_verified_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    email = EXCLUDED.email,
    avatar_url = EXCLUDED.avatar_url,
    status = EXCLUDED.status,
    human_verified_at = EXCLUDED.human_verified_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertUserParams struct {
	ID              uuid.UUID
	DisplayName     string
	Email           *string
	AvatarUrl       *string
	Status          UserStatus
	HumanVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.Status,
		arg.HumanVerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
